/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author profl
 */
public class Agenda2 extends javax.swing.JFrame {

    /**
     * Creates new form agenda
     */
    public Agenda2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblIndice = new javax.swing.JLabel();
        txtIndice = new javax.swing.JTextField();
        pnlCajas = new javax.swing.JPanel();
        lblDni = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblDni1 = new javax.swing.JLabel();
        txtDni1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblDni2 = new javax.swing.JLabel();
        txtDni2 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblDni3 = new javax.swing.JLabel();
        txtDni3 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblDni4 = new javax.swing.JLabel();
        txtDni4 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblDni5 = new javax.swing.JLabel();
        txtDni5 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        pnlBotones = new javax.swing.JPanel();
        btnAtras1 = new javax.swing.JButton();
        btnAtras2 = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTitulo.setBackground(new java.awt.Color(153, 153, 255));
        pnlTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setBackground(new java.awt.Color(204, 255, 204));
        lblTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 204));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Agenda Electrónica");
        lblTitulo.setToolTipText("");
        lblTitulo.setOpaque(true);
        pnlTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 64));

        lblIndice.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        lblIndice.setForeground(new java.awt.Color(0, 0, 204));
        lblIndice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIndice.setText("INDICE");
        pnlTitulo.add(lblIndice, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 100, 32));

        txtIndice.setEditable(false);
        txtIndice.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtIndice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIndice.setText("0");
        pnlTitulo.add(txtIndice, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 130, 32));

        pnlFondo.add(pnlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 64));

        pnlCajas.setOpaque(false);
        pnlCajas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDni.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDni.setForeground(new java.awt.Color(0, 0, 255));
        lblDni.setText("Nro Documento");
        pnlCajas.add(lblDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 5, 350, 35));

        txtDni.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        txtDni.setForeground(new java.awt.Color(153, 153, 153));
        txtDni.setText("Ingrese los datos");
        txtDni.setBorder(null);
        txtDni.setOpaque(false);
        pnlCajas.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 40, 350, 35));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 204));
        pnlCajas.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 70, 350, 10));

        lblDni1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDni1.setForeground(new java.awt.Color(0, 0, 255));
        lblDni1.setText("Nro Documento");
        pnlCajas.add(lblDni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 85, 350, 35));

        txtDni1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        txtDni1.setForeground(new java.awt.Color(153, 153, 153));
        txtDni1.setText("Ingrese los datos");
        txtDni1.setBorder(null);
        txtDni1.setOpaque(false);
        pnlCajas.add(txtDni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 120, 350, 35));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 204));
        pnlCajas.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 150, 350, 10));

        lblDni2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDni2.setForeground(new java.awt.Color(0, 0, 255));
        lblDni2.setText("Nro Documento");
        pnlCajas.add(lblDni2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 165, 350, 35));

        txtDni2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        txtDni2.setForeground(new java.awt.Color(153, 153, 153));
        txtDni2.setText("Ingrese los datos");
        txtDni2.setBorder(null);
        txtDni2.setOpaque(false);
        pnlCajas.add(txtDni2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 200, 350, 35));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 204));
        pnlCajas.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 230, 350, 10));

        lblDni3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDni3.setForeground(new java.awt.Color(0, 0, 255));
        lblDni3.setText("Nro Documento");
        pnlCajas.add(lblDni3, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 5, 350, 35));

        txtDni3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        txtDni3.setForeground(new java.awt.Color(153, 153, 153));
        txtDni3.setText("Ingrese los datos");
        txtDni3.setBorder(null);
        txtDni3.setOpaque(false);
        pnlCajas.add(txtDni3, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 40, 350, 35));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 204));
        pnlCajas.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 70, 350, 10));

        lblDni4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDni4.setForeground(new java.awt.Color(0, 0, 255));
        lblDni4.setText("Nro Documento");
        pnlCajas.add(lblDni4, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 85, 350, 35));

        txtDni4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        txtDni4.setForeground(new java.awt.Color(153, 153, 153));
        txtDni4.setText("Ingrese los datos");
        txtDni4.setBorder(null);
        txtDni4.setOpaque(false);
        pnlCajas.add(txtDni4, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 120, 350, 35));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 204));
        pnlCajas.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 150, 350, 10));

        lblDni5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDni5.setForeground(new java.awt.Color(0, 0, 255));
        lblDni5.setText("Nro Documento");
        pnlCajas.add(lblDni5, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 165, 350, 35));

        txtDni5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        txtDni5.setForeground(new java.awt.Color(153, 153, 153));
        txtDni5.setText("Ingrese los datos");
        txtDni5.setBorder(null);
        txtDni5.setOpaque(false);
        pnlCajas.add(txtDni5, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 200, 350, 35));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 204));
        pnlCajas.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 230, 350, 10));

        pnlFondo.add(pnlCajas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, 800, 240));

        pnlBotones.setOpaque(false);
        pnlBotones.setLayout(null);

        btnAtras1.setBackground(new java.awt.Color(204, 255, 153));
        btnAtras1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnAtras1.setForeground(new java.awt.Color(22, 17, 42));
        btnAtras1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/img/accept_icon-icons.com_74428.png"))); // NOI18N
        btnAtras1.setText("GUARDAR");
        btnAtras1.setOpaque(false);
        pnlBotones.add(btnAtras1);
        btnAtras1.setBounds(1, 0, 266, 80);

        btnAtras2.setBackground(new java.awt.Color(204, 255, 153));
        btnAtras2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnAtras2.setForeground(new java.awt.Color(22, 17, 42));
        btnAtras2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/img/avanzar32.png"))); // NOI18N
        btnAtras2.setText("AVANZAR");
        btnAtras2.setOpaque(false);
        pnlBotones.add(btnAtras2);
        btnAtras2.setBounds(530, 0, 266, 80);

        btnAtras.setBackground(new java.awt.Color(204, 255, 153));
        btnAtras.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(22, 17, 42));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/img/anterior.png"))); // NOI18N
        btnAtras.setText("ATRAS");
        btnAtras.setOpaque(false);
        pnlBotones.add(btnAtras);
        btnAtras.setBounds(270, 0, 266, 80);

        pnlFondo.add(pnlBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 304, 800, 80));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/img/agenda2.jpg"))); // NOI18N
        lblFondo.setOpaque(true);
        pnlFondo.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 400));

        getContentPane().add(pnlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnAtras1;
    private javax.swing.JButton btnAtras2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblDni1;
    private javax.swing.JLabel lblDni2;
    private javax.swing.JLabel lblDni3;
    private javax.swing.JLabel lblDni4;
    private javax.swing.JLabel lblDni5;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIndice;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlCajas;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtDni1;
    private javax.swing.JTextField txtDni2;
    private javax.swing.JTextField txtDni3;
    private javax.swing.JTextField txtDni4;
    private javax.swing.JTextField txtDni5;
    private javax.swing.JTextField txtIndice;
    // End of variables declaration//GEN-END:variables
}
